# Generated by Django 4.1.3 on 2022-12-30 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("gestion", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Estudiante",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("merito_cientifico", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="InformeTesis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "estudiante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestion.estudiante",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Perfil",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("objeto_estudio", models.CharField(max_length=50)),
                ("objetivo_general", models.CharField(max_length=50)),
                ("contexto_problema", models.CharField(max_length=50)),
                (
                    "estado_perfil",
                    models.CharField(
                        choices=[("A", "aprobado"), ("D", "desaprobado")], max_length=1
                    ),
                ),
                (
                    "tema",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="gestion.tema"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tribunal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_usuario", models.CharField(max_length=50)),
                ("correo", models.EmailField(max_length=254)),
                ("nombre", models.CharField(max_length=50)),
                ("apellidos", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Sennalamiento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
                ("descripcion", models.CharField(max_length=50)),
                (
                    "informe_tesis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestion.informetesis",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Profesor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "roles",
                    models.CharField(
                        choices=[("M", "masculino"), ("F", "femenino")], max_length=1
                    ),
                ),
                (
                    "numero_tribunal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestion.tribunal",
                    ),
                ),
                (
                    "perfil_asociado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="gestion.perfil"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestion.usuario",
                        verbose_name="",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="informetesis",
            name="perfil",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="gestion.perfil"
            ),
        ),
        migrations.AddField(
            model_name="informetesis",
            name="profesor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="gestion.profesor"
            ),
        ),
        migrations.AddField(
            model_name="estudiante",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="gestion.usuario",
                verbose_name="",
            ),
        ),
    ]
